###

GET https://goproxy.io/github.com/timandy/routine/@latest

###

GET https://goproxy.io/github.com/timandy/routine/@v/v1.0.4.zip

###

GET https://goproxy.io/github.com/timandy/routine/@v/list

###

GET https://goproxy.io/github.com/timandy/routine/@v/v1.0.4.info

###

GET https://goproxy.io/github.com/timandy/routine/@v/v1.0.4.mod

###

GET https://goproxy.io/github.com/timandy/routine/@v/v1.0.4.list


###

GET https://proxy.golang.org/github.com/timandy/routine/@v/v1.0.4.zip