on:
  push:
    branches:
      - main
      - release/**
      - feature/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ aarch64, x64 ]
        go: [ 1.13, 1.14, 1.15, 1.16, 1.17, 1.18 ]
    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: 'Test with ${{ matrix.go }} amd64'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -v ./

      - name: 'Build with ${{ matrix.go }} arm64'
        if: ${{ matrix.arch == 'aarch64' }}
        env:
          GOARCH: arm64
        run: go test -v ./

      - name: 'Init arm env with ${{ matrix.go }} aarch64'
        if: ${{ matrix.arch == 'aarch64' }}
        env:
          GOARCH: arm64
          CGO_ENABLED: 0
        run: |
          # Non-host *.syso files are missing from the Go toolchains provided
          # by setup-go. See https://github.com/actions/setup-go/issues/181.
          sudo apt-get update -y && \
          curl --location --output ${{ env.GOROOT }}/src/runtime/race/race_linux_arm64.syso \
            https://github.com/golang/go/raw/release-branch.go${{ matrix.go }}/src/runtime/race/race_linux_arm64.syso && \
          sudo apt install gcc-aarch64-linux-gnu && \
          CC=aarch64-linux-gnu-gcc CC_FOR_TARGET=gcc-aarch64-linux-gnu go test -c -o hacktest.test && \
          rm hacktest.test

      - name: 'Test with ${{ matrix.go }} on ${{ matrix.arch }}'
        if: ${{ matrix.arch != 'x64' }}
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: bullseye
          dockerRunArgs: --mount type=bind,source="$(pwd)",target=/checkout,readonly
          run: |
            find /checkout -name '*.test' -type f -executable -print0 | \
              xargs -t -0 -I '{}' sh -c '{} -test.v'
