on:
  push:
    branches:
      - main
      - release/**
      - feature/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ x64 ]
        go: [ 1.13, 1.14, 1.15, 1.16, 1.17, 1.18 ]
    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: 'Test with ${{ matrix.go }} amd64'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -v ./
